title: Minh Pham # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Product and data analytics. I wish to leverage my engineering and data analytics skills to build great products and make an impact! I have a wide range of experience from consulting, product management, to product design and engineering.
  <br><br>
  Key achievements: McKinsey Fall 2020 Case Competition Winner. <a href="https://tinyurl.com/ydxbjwuf">View The Slide Deck</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/minh-t-pham/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
