title: Minh Pham 

avatar: "/profilepic.jpg"


description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  A Learner and A Traveler
  <br><br>
  <a href="https://www.linkedin.com/in/anhpham96/">LinkedIn</a> |
  <a href="https://github.com/apham15">GitHub</a> |
  <a href="/pdf/Anh Pham - DS.pdf">Resume</a> |
  <a href="https://public.tableau.com/profile/anh.pham7622#!/">Tableau</a> 
  <p align="justify">
  I am pursing an MS degree in Business Analytics at Kellstadt Business School, DePaul University, where I hold the office of Vice President in the Kellstadt Business Analytics Organization.
  <br>  <br>
  I love applying Machine Learning Algorithms to bring insightful information for everyone.
  <br><br>
  </p>
theme: jekyll-theme-minimal

