title: John Doe 

logo: "/images/headshot_round.jpg?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  Product & Data Analytics 
  <br><br>
  I'm current a Masters in Quantitative Management, Business Analytics at Duke University (Fuqua School of Business). I wish to leverage my engineering and data analytics skills to build great products and make an impact! I have a wide range of experience from consulting, product management, to product design and engineering. I held an undergraduate degree in Mechanical Engineering, specialized in product design at Case Western Reserve University. 
  <br><br>
  Highlighted achievement: McKinsey Fall 2020 Case Competition Winner.
  <a href="https://tinyurl.com/ydxbjwuf">Winning Slide Deck</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">LinkedIn</a> 
  <a href="https://github.com/minhtpham">GitHub</a> 
  <a href="https://public.tableau.com/app/profile/minh.pham2728#!/">Tableau Dashboard</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
